### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by kernelcoffee** [kernelcoffee/SteamSelfGifter#10]
trigger a 429 after a while, seems new.

**Comment by Dabu-dot** [comment]
Agreed, I thought it was only me because I left it run at night too lmao

**Comment by MajorLOL** [comment]
Same problem here :(,
Btw that last update was great, thanks for your work ;)

**Comment by Dabu-dot** [comment]
Here are the new values for their Request Rate limits btw:

- 120 requests per minute
- 2,400 requests per hour
- 14,400 requests per day

They explain it's for DDOS prevention but obviously it's against bots aswell lol. New delays between a set of requests should do the trick.

_[Source](https://www.steamgifts.com/discussion/yLOhv/rate-limiting-limits)_

**Comment by kernelcoffee** [comment]
Awesome, thanks
I'm trying to limit as much as I can the amount of request the bot is doing, guess it's not enough.
I'll increase the delays for now but now that I read that they seems cool with scripts and bot as long as they don't hammer the server, I'll have the rethink a more smarter bahavior around these rate limits

**Comment by Dabu-dot** [comment]
Sure, we'll be there if you need testing or infos as well. 
Some users seems still reluctant about bots and they even discussed about the integration of an API soon to control more the request per user / script linked to SG.
As long as SSG won't cause too much loads on the servers, I'm pretty sure it is still safe. 

CG (admin of SteamGifts) also has obviously logs of users that reach the error 429 and can see the amount of requests made in a set time. He catched unhumans behaviors on some users in the comments below his post. 

As a suggestion, I guess it could be interesting to add a "killswitch" if the bot detect the error 429 and relaunch itself after a time selected by the user in the config.ini

**Comment by kernelcoffee** [comment]
After investigation I found a bug in a edge case situation, so far I was ignoring games that don't have a reference on steam (either too old, trash game, or publisher removed it) which in most cases doesn't matter.

SG added advertised games that appears at the top of games lists which would get caught in the game list parsing, usually I would catch it because the same game would be parse twice (and hide it), but not if the game doesn't exist on steam (skipped), so the parser would get caught in a endless loop where the list to parse would always return at least one game.

Game not existing on steam are now hidden directly on SG.
(so I might be part of the reason why SG started rate limit..)

anyway, I increased the waiting period between request to stay within the limit rate, so should be fixed now.

**Comment by kernelcoffee** [comment]
I'm keeping the ticket open for now, I'll close it later this week if no issue is reported on this matter.

**Comment by MajorLOL** [comment]
not having any problems since last update and its even working better then before.

**Comment by MajorLOL** [comment]
Quick question is there anyway we can change the check time manual?
Changing it in the config file would be best.

Would like it to change it to every 2-3 or so

**Comment by kernelcoffee** [comment]
not currently, since the minimal time range for a giveaway is 1h, the check time is between 16 and 32 minutes (1000/2000 seconds), so it should catch all the giveaways.
It doesn't hurt to make it configurable, I'll add it to the todo list.

**Comment by kernelcoffee** [comment]
It's been a few days, there doesn't seem to be any problems anymore, closing this issue
