### ISSUE TITLE
ERROR steamselfgifter.py::get_games::70 - Failed to parse page https://www.steamgifts.com/giveaways/search?page=1&type=wishlist: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by legendofmiracles** [kernelcoffee/SteamSelfGifter#11]
Does this error influence anything?

This is running in a docker container, on a rpi.

**Comment by MajorLOL** [comment]
Have not received this message yet, Do you even have games on your wishlist on steam?

**Comment by legendofmiracles** [comment]
Yes, I have 21 Games on my wishlist.

**Comment by MajorLOL** [comment]
My last 2 cent 
![image](https://user-images.githubusercontent.com/56225967/106721803-72185900-6605-11eb-87dc-ae32c9a5b404.png)
are games being shown under Wishlist?

Maybe rights problem with your steam profiel?
if not you need to wait for Kernelcoffee to answere.

**Comment by legendofmiracles** [comment]
Yes they are. 
![image](https://user-images.githubusercontent.com/30902201/106728741-a8090d80-6604-11eb-8c1c-7d7d66b010c0.png)


(whoops, wrong menu)
![image](https://user-images.githubusercontent.com/30902201/106728929-df77ba00-6604-11eb-895a-9973ab4abb1a.png)

**Comment by kernelcoffee** [comment]
It means the parsing of the whislist page failed, does it occur everytime or occasionnaly ? Are the giveaway being entered ?

**Comment by legendofmiracles** [comment]
everytime.
![image](https://user-images.githubusercontent.com/30902201/106856409-4d2fee80-66b6-11eb-9e96-6166f21013de.png)

And i don't think that it's entering the giveaways, as there were two giveaways of games that were on my wishlist (skyrim and overcooked, they're definitely meeting the criteria), but it didn't enter them.

**Comment by kernelcoffee** [comment]
looks like it's not working at all, it's not even gathering the points
Is your cookie still valid ?

Otherwise can you setup the logs to debug ?
in the config.ini file you should have `log_level = INFO`, set it up to `log_level = DEBUG` and restart the container to gather the logs (this will be very verbose), copy paste them into a gists and share it to me.
I will take a closer look this week-end.

**Comment by legendofmiracles** [comment]
Ah.. it was a somehow wrong session id.. no idea how.

Maybe there should be a better error, when the session id is wrong. 

Thanks anyways!
