### ISSUE TITLE
Cant connect to the site

### ISSUE THREAD

**Issue by MajorLOL** [kernelcoffee/SteamSelfGifter#3]
Hi again,

I am receiving the following error when trying to run the bot since the update of docker and synology.

Cant connect to the site : HTTPSConnectionPool(host='www.steamgifts.com', port=443): Max retries exceeded with url: /giveaways/search?page=1&type=wishlist (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a13d89350>: Failed to establish a new connection: [Errno -3] Try again')) | stdout
-- | --

**Comment by kernelcoffee** [comment]
I'll look into, but I don't have a synology in order to reproduce. (no promise here)

**Comment by MajorLOL** [comment]
It was a DNS issue on my end, when restarted docker pi-hole and my router could not connect anymore with each other and so my network gave problems.

Thanks for looking into it and making time for it.
