### ISSUE TITLE
My config.ini isn't generated

### ISSUE THREAD

**Issue by Dabu-dot** [kernelcoffee/SteamSelfGifter#9]
Hey, thanks for working on this project.

I'm kinda confused about how the project work though, isn't the config.ini supposed to be generated automatically ?
I've mounted my config volume to the config folder of my choice and thought that it would be created on start (without any PHPSESSID yet obviously).

Do you have any details on how I could make it run ?

**Comment by Dabu-dot** [comment]
I'm just dumb and didn't saw that you've provided a config.ini sample in your repository.
I should simply stop rushing things lol, thanks anyway.

**Comment by kernelcoffee** [comment]
Hey !
Thanks for using this project, there are a lot of thing to be worked out still ^^

I recently added a way to add the missing parameters with default values in the config file if they are missing, however I didn't check the behaviour if the config is missing, I'll add it to my todo list.

**Comment by Dabu-dot** [comment]
It's running smoothly from 30 minutes in any case, I'm eager to see what you'll come up next with this.

And thanks a lot again, this is truly a life-saver ;)
